import { 
    aiPrompts,
    pagemark,
    talentmatch,
    codexai,
    intellislide,
    echogram,
    remindly,
    creatifyAI,
    pennyplan,
    coinstream,
    netchat,
    orbitstaff,
    quickSumAi,
    planvault, 
    delectable,
    slideTubeAi,
    promptHub,
    thankfulart,
    codraft,
    medimatrix,
    snapsavvy,
    midin ,
    detectify,
    motohub ,
    shopoholics,
    shelterium,
    hireIQ,
    coverflow
   } from "@public/projects/projectSources";

export type ProjectKind = "frontend" | "backend" | "fullstack";

export type ProjectEndpoint = {
  readonly method: "GET" | "POST" | "PUT" | "PATCH" | "DELETE";
  readonly path: string;
  readonly purpose: string;
};

export const projects = [
   
      {
      id: 0,
      title: "Codraft — Real-time collaboration and document editing",
      description:
        "Collaborative editor with live presence and secure sharing (Liveblocks + Clerk). Shipped end-to-end UI, auth, and persistence—focused on low-latency typing and clear UX under concurrent edits.",
      image: codraft,
      tags: ["Nextjs", "Typescript", "Tailwind", "Sentry", "Liveblocks", "Clerk"],
      category: "web app",
      kind: "frontend" as const,
      github: "https://github.com/engraya/codraft",
      webapp: "https://codraft-io.vercel.app/",
    },
    {
      id: 1,
      title: "Delectable AI — Global recipes, smart search & recipe copilot 🌍🍽️",
      description:
        "Discover dishes from a large recipe catalog with trending picks and cuisine-style browsing. Describe what you want in plain English and AI turns it into search filters (cuisine, diet, intolerances, time, and more). On every recipe, Recipe Copilot is page-aware—ask about substitutions, scaling, simpler steps, or allergy-minded swaps—with requests handled on a backend so API keys stay off the client.",
      image: delectable,
      tags: ["React", "TypeScript", "Tailwind CSS", "Hono", "Gemini"],
      category: "web app",
      kind: "fullstack" as const,
      github: "https://github.com/engraya/Delectable",
      webapp: "https://delectable.vercel.app/",
    },
    {
      id: 2,
      title: "HireIQ — Hiring and job discovery platform",
      description:
        "Full-stack Next.js + Express + MongoDB: listings, applications, and discovery flows with React Query on the client. Emphasis on responsive UX and reliable API integration.",
      image: hireIQ,
      tags: ["Nextjs", "Javascript", "Tailwind","React", "Nodejs", "Express", "MongoDB"],
      category: "web app",
      kind: "fullstack" as const,
      github: "https://github.com/engraya/hireIQ",
      webapp: "https://hire-iq-123.vercel.app/",
    },
    {
      id: 3,
      title: "CoverFlow — AI cover letters tailored to job posts",
      description:
        "CoverFlow AI is an AI-powered cover letter generation platform built to simplify one of the most frustrating parts of the job application process — writing personalized cover letters for every role.",
      image: coverflow,
      tags: ["Next.js", "React", "Tailwind CSS", "GeminiAI", "TypeScript", "ShadCn UI"],
      category: "web app",
      kind: "frontend" as const,
      github: "https://github.com/engraya/CoverFlow",
      webapp: "https://cover-flow.vercel.app/",
    },
    {
      id: 4,
      title: "SlideTube-AI – Instantly Turn YouTube Videos into Presentations 🎥➡️",
      description:
        "SlideTube-AI transforms any YouTube video into a professional, editable presentation🌐💬",
      image: slideTubeAi,
      tags: ["React", "Nextjs", "Typescript", "TailwindCSS", "Shadcn UI", "PostgreSQL", "Clerk", "Gemini-AI"],
      category: "web app",
      kind: "frontend" as const,
      github: "https://github.com/engraya/slideTube-ai",
      webapp: "https://slidetube-ai.vercel.app/",
    },
    {
      id: 5,
      title: "IntelliSlide-AI –Instantly Generate Stunning Presentations with AI 🧠",
      description:
        "Turn your ideas into professional PowerPoint slides in seconds!  🌐💬",
      image: intellislide,
      tags: ["React", "Nextjs", "TailwindCSS", "Typescript", "ShadCn", "Python", "FastAPI"],
      category: "web app",
      kind: "frontend" as const,
      github: "https://github.com/engraya/intelliSlide-ai",
      webapp: "https://intelli-slide-ai.vercel.app/",
    },
    {
      id: 6,
      title: "Echogram – Explore Life Through an Interactive Social Feed 📸🎥🌍",
      description:
        "Share your moments with friends and the world through stunning images and posts 🌐💬",
      image: echogram,
      tags: ["React", "Appwrite", "TailwindCSS", "Typescript", "TanstackQuery"],
      category: "web app",
      kind: "frontend" as const,
      github: "https://github.com/engraya/echogram",
      webapp: "https://echogram-io.vercel.app/",
    },
    {
      id: 7,
      title: "CodexAI – Instantly Generate Production-Ready Components with AI ⚛️💡",
      description:
        "With the power of AI, Turn your ideas into clean, production-ready code components with just a prompt.",
      image: codexai,
      tags: ["Nextjs", "Typescript", "TailwindCSS","Clerk", "Gemini-AI"],
      category: "web app",
      kind: "frontend" as const,
      github: "https://github.com/engraya/Codex-AI",
      webapp: "https://codex-ai-phi-two.vercel.app/",
    },
    {
      id: 8,
      title: "Medimatrix – Patient Record & Appointment Management System 🏥📋🩺",
      description:
        "Manage Patient's records, appointments, and more—all in one place",
      image: medimatrix,
      tags: ["Nextjs", "Typescript", "TailwindCSS", "Shadcn UI", "Appwrite", "Clerk", "Sentry"],
      category: "web app",
      kind: "frontend" as const,
      github: "https://github.com/engraya/medimatrix",
      webapp: "https://medimatrix.vercel.app/",
    },
    {
      id: 9,
      title: "NetChat – AI-Powered Web Interaction Assistant 🤖💬🌐",
      description:
        "NetChat is an innovative AI-powered app that transforms how you interact with websites.",
      image: netchat,
      tags: ["Nextjs", "Typescript", "TailwindCSS", "Shadcn UI", "Clerk", "Vercel AI SDK", "UPSTASH"],
      category: "web app",
      kind: "frontend" as const,
      github: "https://github.com/engraya/netchat",
      webapp: "https://netchat-io.vercel.app/",
    },
    {
      id: 10,
      title: "Detectify-AI – Real-Time Object Detection Powered by AI 🎯🧠📷",
      description:
        "Discover the future of object detection with Detectify AI.",
      image: detectify,
      tags: ["Nextjs", "Typescript", "TailwindCSS", "Threejs", "Tensorflowjs"],
      category: "web app",
      kind: "frontend" as const,
      github: "https://github.com/engraya/detectify-ai",
      webapp: "https://detectify-ai.vercel.app/",
    },
    {
      id: 11,
      title: "PennyPlan – Smart Finance Management with AI-Powered Insights 💰📊🤖",
      description:
        "Manage your finances effortlessly with AI-powered insights and personalized financial advice",
      image: pennyplan,
      tags: ["Nextjs", "Typescript", "TailwindCSS", "Shadcn UI", "Drizzle", "PostgreSQL"],
      category: "web app",
      kind: "frontend" as const,
      github: "https://github.com/engraya/pennyplan",
      webapp: "https://pennyplan.vercel.app/",
    },
    {
      id: 12,
      title: "PlanVault – Simplify Subscription Management & Payments 💼⚙️",
      description:
        "Fantastic UI/UX Payment platform that automates billing, invoicing, and subscription management for businesses.",
      image: planvault,
      tags: ["Nextjs", "Typescript", "TailwindCSS", "Stripe"],
      category: "web app",
      kind: "frontend" as const,
      github: "https://github.com/engraya/PlanVault",
      webapp: "https://planvault.vercel.app/",
    },
    {
      id: 13,
      title: "Thankful Art – Create Personalized Thank You Cards in Seconds ✨💌🎨",
      description:
        "ThankfulArt is a web app designed to help you Create Your Perfect Thank You Card in Seconds",
      image: thankfulart,
      tags: ["Nextjs", "Typescript", "TailwindCSS", "Shadcn UI"],
      category: "web app",
      kind: "frontend" as const,
      github: "https://github.com/engraya/thankful_art",
      webapp: "https://thankfulart.vercel.app/",
    },
    {
      id: 14,
      title: "Creatify_AI – Instantly Generate SEO-Friendly Content for Web 🧠✍️🚀",
      description:
        "Creatify_AI empowers businesses, marketers, and creators with high-quality, SEO-friendly contents in seconds",
      image: creatifyAI,
      tags: ["React", "Nextjs", "Typescript", "TailwindCSS", "Shadcn UI", "PostgreSQL", "Clerk", "Stripe", "Docker", "Gemini-AI"],
      category: "web app",
      kind: "frontend" as const,
      github: "https://github.com/engraya/creatify_AI",
      webapp: "https://creatify-ai-pro.vercel.app/",
    },
    {
      id: 15,
      title: "Motohub – Explore the World’s Sleekest, Most Stylish Cars 🌍🚗🔥b",
      description:
        "MotoHub - the hottest spot on the web to explore sleek, stylish, and cutting-edge cars from around the globe! 🌐🔥",
      image: motohub,
      tags: ["Nextjs", "Typescript", "TailwindCSS", "HeadlessUI", "React"],
      category: "web app",
      kind: "frontend" as const,
      github: "https://github.com/engraya/motohub",
      webapp: "https://motohub-io.vercel.app/",
    },
    {
      id: 16,
      title: "Shelterium – Buy, Rent & Sell Properties with Real Estate App 🏠🔑📱",
      description:
        "Shelterium, the ultimate real estate app for buying, renting, and selling properties. 🏠🔑✨🌟",
      image: shelterium,
      tags: ["Nextjs", "Typescript", "TailwindCSS", "React"],
      category: "web app",
      kind: "frontend" as const,
      github: "https://github.com/engraya/Shelterium",
      webapp: "https://shelterium.vercel.app/",
    },
    {
      id: 17,
      title: "QuickSumAI – Instantly Summarize Long Articles with AI 🧠📄⚡",
      description:
        "🌐 QuickSum AI is here to transform how you consume content!, a go-to solution for summarizing long articles in seconds. ⏳",
      image: quickSumAi,
      tags: ["React", "Typescript", "TailwindCSS", "Redux", "Redux Toolkit"],
      category: "web app",
      kind: "frontend" as const,
      github: "https://github.com/engraya/QuickSum-AI",
      webapp: "https://quicksum-ai.vercel.app/",
    },
    {
      id: 18,
      title: "CoinStream – Real-Time Crypto Stats, Market Trends & Coin Insight 💹🪙",
      description:
        "Explore detailed information on a wide range of coins, from market capitalization to trading volume.",
      image: coinstream,
      tags: ["Nextjs", "Typescript", "TailwindCSS"],
      category: "web app",
      kind: "frontend" as const,
      github: "https://github.com/engraya/coinStream",
      webapp: "https://coinstream.vercel.app/",
    },
      {
      id: 19,
      title: "Shopoholics – Ecommerce App for Seamless Online Shopping 🛍️🛒⚙️",
      description:
        "Shopoholics, an open-source Fullstack ecommerce app designed to revolutionize your online shopping experience! 🛒",
      image: shopoholics,
      tags: ["Nextjs", "Typescript", "TailwindCSS", "Sanity", "Stripe", "ShadCN", "React"],
      category: "web app",
      kind: "frontend" as const,
      github: "https://github.com/engraya/shopoHolics",
      webapp: "https://shopoholics.vercel.app/",
    },
    {
      id: 20,
      title: "PromptHub – Discover, Organize & Share AI Prompts Effortlessly 💡📚🤖",
      description:
        "The ultimate platform for generating, sharing, and discovering prompts for every need",
      image: promptHub,
      tags: ["Nextjs", "Typescript", "Tailwind", "Next-Auth", "Shadcn UI"],
      category: "web app",
      kind: "frontend" as const,
      github: "https://github.com/engraya/PromptHub",
      webapp: "https://prompthub-io.vercel.app/",
    },
    {
      id: 21,
      title: "Midin Project – Saving Communities Through Humanitarian Action 🌍❤️🤝",
      description:
        "Web Application for a dedicated humanitarian organization committed to creating positive change in communities.",
      image: midin,
      tags: ["React", "Tailwind", "Javascript"],
      category: "web app",
      kind: "frontend" as const,
      github: "https://github.com/engraya/MIDIN-Org-Web-Project",
      webapp: "https://midin.vercel.app/",
    },
    {
      id: 22,
      title: "OrbitStaff – Smart Workforce & Staff Management Made Simple 🧑‍💼📊🚀",
      description:
        "OrbitStaff is a modern staff management solution designed to simplify how businesses manage workforce data.",
      image: orbitstaff,
      tags: ["React", "TailwindCSS", "Typescript", "Redux"],
      category: "web app",
      kind: "frontend" as const,
      github: "https://github.com/engraya/orbitStaff",
      webapp: "https://orbitstaff.vercel.app/",
    },
      {
      id: 23,
      title: "Remidly – Smart Task & Reminder App to Organize Your Life ⏰📝✅",
      description:
        "Organize, prioritize, and conquer your to-dos with ease, whether it’s work, personal tasks, or long-term goals.",
      image: remindly,
      tags: ["React", "Nexjs", "Typescript", "TailwindCSS", "PostgreSQL", "ShadCnUI", "Clerk", "NeonDB"],
      category: "web app",
      kind: "frontend" as const,
      github: "https://github.com/engraya/remindly",
      webapp: "https://remindly-io.vercel.app/",  
    },
        {
      id: 24,
      title: "TalentMatchAI – AI-Powered Intelligent Job Matching App",
      description:
        " TalentMatchAI analyzes your skills, matches them with the best job opportunities, and even helps you apply – all in one seamless experience! 🔍✨",
      image: talentmatch,
      tags: ["Nextjs", "Typescript", "TailwindCSS", "Shadcn UI", "AI", "Zustand"],
      category: "web app",
      kind: "frontend" as const,
      github: "https://github.com/engraya/TalentMatch-AI",
      webapp: "https://talent-match-ai-jade.vercel.app/",
    },
      {
      id: 25,
      title: "Snapsavvy - Optimize your Photos Powered by AI 📷",
      description:
        " AI-powered application designed to revolutionize the way you enhance and restore your photos.",
      image: snapsavvy,
      tags: ["Nextjs", "Typescript", "TailwindCSS", "Shadcn UI", "Stripe", "Unsplash AI", "Clerk", "MongoDB"],
      category: "web app",
      kind: "frontend" as const,
      github: "https://github.com/engraya/SnapSavvy",
      webapp: "https://snapsavvy.vercel.app/",
    },
    {
      id: 26,
      title: "Core Post Backend — blog & engagement API",
      description: "Versioned Express REST API (`/api/v1`) for posts, nested comments, likes, and bookmarks on MongoDB. Users register and verify email via OTP email (Nodemailer); JWT protects mutations, with an extra database-backed verified-email check for write operations. List endpoints support query pagination (`page`), and auth-sensitive routes use express-rate-limit. Vitest and Supertest cover HTTP behavior against MongoDB when available.",
      image: pagemark,
      tags: [
        "Node.js",
        "TypeScript",
        "Express",
        "MongoDB",
        "Mongoose",
        "JWT",
        "Joi",
        "Nodemailer",
        "Vitest"
      ],
      category: "API",
      kind: "backend",
      github: "https://github.com/engraya/core-post-backend",
      apiDocs: null,
      baseUrl: "https://core-post.onrender.com/api/v1",
      _baseUrlNote: "Host appears in README as https://core-post.onrender.com; `/api/v1` is the prefix in src/app.ts. Replace if your deployment differs or README is outdated.",
      auth: "JWT via `Authorization` cookie or `Authorization: Bearer`; email verification enforced with DB check (`isVerified`) on protected writes.",
      deployment: "Documented for Render (render.yaml: npm build + node dist/index.js, PORT 8000); multi-stage Docker image (node:22-alpine) — hosting choice not verified beyond config.",
      endpoints: [
        { "method": "GET", "path": "/", "purpose": "JSON hello / basic liveness response." },
        { "method": "POST", "path": "/api/v1/auth/register", "purpose": "Create account (rate-limited)." },
        { "method": "POST", "path": "/api/v1/auth/login", "purpose": "Authenticate and obtain JWT (rate-limited)." },
        { "method": "POST", "path": "/api/v1/auth/logout", "purpose": "Logout for authenticated user." },
        { "method": "PATCH", "path": "/api/v1/auth/verify-account", "purpose": "Confirm email with verification code (rate-limited)." },
        { "method": "GET", "path": "/api/v1/posts", "purpose": "Paginated list of posts (`page` query)." },
        { "method": "GET", "path": "/api/v1/posts/:_id", "purpose": "Single post; optional JWT enriches liked/bookmarked-by-me flags." },
        { "method": "POST", "path": "/api/v1/posts/create", "purpose": "Create post (authenticated + verified)." },
        { "method": "GET", "path": "/api/v1/posts/:postId/comments", "purpose": "Paginated comments for a post." },
        { "method": "POST", "path": "/api/v1/posts/:postId/like", "purpose": "Like a post (authenticated + verified)." },
        { "method": "GET", "path": "/api/v1/posts/:postId/likes/count", "purpose": "Public like count for a post." },
        { "method": "PATCH", "path": "/api/v1/users/me", "purpose": "Update current user profile (authenticated)." },
        { "method": "GET", "path": "/api/v1/users/me/bookmarks", "purpose": "Paginated saved posts for current user." },
        { "method": "GET", "path": "/api/v1/users/:id", "purpose": "User profile with posts." }
      ],
      architectureSummary: [
        "`createApp()` in src/app.ts mounts versioned routers under `/api/v1` and applies helmet, compression, CORS, cookie-parser, json/urlencoded parsers.",
        "Routers in src/routers/* delegate to controllers in src/controllers/*.",
        "Controllers call services in src/services/*; Joi validation is centralized in src/utils/validator.ts.",
        "Mongoose models in src/models/* persist to MongoDB; index.ts connects via MONGODB_URI then listens.",
        "Cross-cutting: asyncHandler, AppError + errorHandler, isAuthenticated / optionalAuthenticated / isVerified, and rate limiters on auth routes.",
        "No OpenAPI/Swagger spec or `.github/workflows` in repo; tests use Vitest + Supertest in src/app.test.ts."
      ]
    },
    {
      id: 27,
      title: "Jobnest API — job board backend",
      description:
        "REST API for job postings and applications built with Express and TypeScript. Mongoose models link users to jobs they create and jobs they apply to, with JWT-based sessions and role checks for admin-only user deletion. Request bodies for registration and login are validated with Joi; passwords are hashed with bcrypt. Routes are grouped under /api and /api/auth. No OpenAPI spec or health-check route is present in the repository.",
      image: aiPrompts,
      tags: [
        "Node.js",
        "TypeScript",
        "Express",
        "Mongoose",
        "MongoDB",
        "JWT",
        "Joi",
        "Helmet",
        "bcryptjs"
      ],
      category: "API",
      kind: "backend",
      github: "https://github.com/engraya/hirescape-api",
      baseUrl: "https://jobnest-jx9f.onrender.com",
      _baseUrlNote: "Not documented in repo; replace when deployment URL is known.",
      auth: "JWT via httpOnly cookie `Authorization` or `Authorization: Bearer <token>`",
      deployment: "Documented for Render (render.yaml: npm build + node dist/index.js, PORT 8000); multi-stage Docker image (node:22-alpine) — hosting choice not verified beyond config.",
      endpoints: [
        { "method": "GET", "path": "/", "purpose": "Returns a short welcome JSON message." },
        { "method": "POST", "path": "/api/auth/register", "purpose": "Create a user account with validated registration fields." },
        { "method": "POST", "path": "/api/auth/login", "purpose": "Authenticate and issue a JWT (cookie and JSON body)." },
        { "method": "POST", "path": "/api/auth/logout", "purpose": "Clear the auth cookie for the signed-in user." },
        { "method": "GET", "path": "/api/auth/users", "purpose": "List users (authenticated)." },
        { "method": "GET", "path": "/api/auth/users/:id", "purpose": "Fetch one user by id (authenticated)." },
        { "method": "DELETE", "path": "/api/auth/users/:id", "purpose": "Delete a user by id (authenticated admin only)." },
        { "method": "GET", "path": "/api/jobs", "purpose": "List all jobs with sorting and populated relations." },
        { "method": "GET", "path": "/api/jobs/:id", "purpose": "Fetch a single job by id." },
        { "method": "POST", "path": "/api/jobs", "purpose": "Create a job for the authenticated user." },
        { "method": "PUT", "path": "/api/jobs/:id", "purpose": "Update a job if the caller is the creator." },
        { "method": "DELETE", "path": "/api/jobs/:id", "purpose": "Delete a job if the caller is the creator." },
        { "method": "GET", "path": "/api/jobs/user/created", "purpose": "List jobs created by the authenticated user." },
        { "method": "GET", "path": "/api/jobs/user/applied", "purpose": "List jobs the authenticated user has applied to." },
        { "method": "POST", "path": "/api/jobs/apply/:id", "purpose": "Record an application to a job for the authenticated user." }
      ],
      omittedEndpointsForCap15: [
        "DELETE /api/jobs/created/:id — delete own job (creator check).",
        "DELETE /api/jobs/applied/:id — remove a job from the user’s applied list."
      ],
      architectureSummary: [
        "Express app in src/index.ts mounts auth and job routers and connects Mongoose when MONGODB_URI is set.",
        "HTTP routes live under src/routers/authRouter.ts and src/routers/jobRouter.ts (prefixes /api/auth and /api).",
        "Controllers in src/controllers/* implement handlers and call Mongoose models User and Job.",
        "Joi schemas in src/utils/validator.ts validate auth payloads; bcrypt hashing in src/utils/hashing.ts.",
        "isAuthenticated verifies JWT from cookie or Bearer header and attaches req.user; isAdmin gates admin-only deletes.",
        "No dedicated API versioning segment (e.g. /v1); public surface uses /api and /api/auth."
      ]
    },
  ] as const;
