import { 
    aiPrompts,
    talentmatch,
    codexai,
    intellislide,
    echogram,
    remindly,
    creatifyAI,
    genLetterai,
    pennyplan,
    coinstream,
    netchat,
    orbitstaff,
    quickSumAi,
    planvault,
    pagemark, 
    delectable,
    hirescape,
    slideTubeAi,
    promptHub,
    thankfulart,
    polyglotter,
    codraft,
    medimatrix,
    snapsavvy,
    festivo,
    midin ,
    postcraftai,
    detectify,
    motohub ,
    movies,
    weather ,
    shopoholics,
    shelterium,
   } from "@public/projects/projectSources";

export const projects = [
   
      {
      id: 0,
      title: "Codraft — Real-time collaboration and document editing",
      description:
        "Collaborative editor with live presence and secure sharing (Liveblocks + Clerk). Shipped end-to-end UI, auth, and persistence—focused on low-latency typing and clear UX under concurrent edits.",
      image: codraft,
      tags: ["Nextjs", "Typescript", "Tailwind", "Sentry", "Liveblocks", "Clerk"],
      category: "web app",
      github: "https://github.com/engraya/codraft",
      webapp: "https://codraft-io.vercel.app/",
    },
    {
      id: 1,
      title: "GenLetter AI — AI cover letters tailored to job posts",
      description:
        "Gemini-backed flow: job context in → tailored letter out with live preview and export. Built for speed (seconds per draft) while keeping tone consistent with the posting.",
      image: genLetterai,
      tags: ["Next.js", "React", "Tailwind CSS", "GeminiAI", "TypeScript", "ShadCn UI", "Vercel"],
      category: "web app",
      github: "https://github.com/engraya/genLetter-ai",
      webapp: "https://gen-letter-ai.vercel.app/",
    },
    {
      id: 2,
      title: "Hirescape — Hiring and job discovery platform",
      description:
        "Full-stack Next.js + Express + MongoDB: listings, applications, and discovery flows with React Query on the client. Emphasis on responsive UX and reliable API integration.",
      image: hirescape,
      tags: ["Nextjs", "Javascript", "Tailwind","React", "React Query", "Nodejs", "Express", "MongoDB"],
      category: "web app",
      github: "https://github.com/engraya/hirescape",
      webapp: "https://hirescape.vercel.app/",
    },
    {
      id: 3,
      title: "Creatify_AI – Instantly Generate SEO-Friendly Content for Web 🧠✍️🚀",
      description:
        "Creatify_AI empowers businesses, marketers, and creators with high-quality, SEO-friendly contents in seconds",
      image: creatifyAI,
      tags: ["React", "Nextjs", "Typescript", "TailwindCSS", "Shadcn UI", "PostgreSQL", "Clerk", "Stripe", "Docker", "Gemini-AI"],
      category: "web app",
      github: "https://github.com/engraya/creatify_AI",
      webapp: "https://creatify-ai-pro.vercel.app/",
    },
    {
      id: 4,
      title: "SlideTube-AI – Instantly Turn YouTube Videos into Presentations 🎥➡️",
      description:
        "SlideTube-AI transforms any YouTube video into a professional, editable presentation🌐💬",
      image: slideTubeAi,
      tags: ["React", "Nextjs", "Typescript", "TailwindCSS", "Shadcn UI", "PostgreSQL", "Clerk", "Gemini-AI"],
      category: "web app",
      github: "https://github.com/engraya/slideTube-ai",
      webapp: "https://slidetube-ai.vercel.app/",
    },
    {
      id: 5,
      title: "IntelliSlide-AI –Instantly Generate Stunning Presentations with AI 🧠",
      description:
        "Turn your ideas into professional PowerPoint slides in seconds!  🌐💬",
      image: intellislide,
      tags: ["React", "Nextjs", "TailwindCSS", "Typescript", "ShadCn", "Python", "FastAPI"],
      category: "web app",
      github: "https://github.com/engraya/intelliSlide-ai",
      webapp: "https://intelli-slide-ai.vercel.app/",
    },
    {
      id: 6,
      title: "Echogram – Explore Life Through an Interactive Social Feed 📸🎥🌍",
      description:
        "Share your moments with friends and the world through stunning images and posts 🌐💬",
      image: echogram,
      tags: ["React", "Appwrite", "TailwindCSS", "Typescript", "TanstackQuery"],
      category: "web app",
      github: "https://github.com/engraya/echogram",
      webapp: "https://echogram-io.vercel.app/",
    },
    {
      id: 7,
      title: "CodexAI – Instantly Generate Production-Ready Components with AI ⚛️💡",
      description:
        "With the power of AI, Turn your ideas into clean, production-ready code components with just a prompt.",
      image: codexai,
      tags: ["Nextjs", "Typescript", "TailwindCSS","Clerk", "Gemini-AI"],
      category: "web app",
      github: "https://github.com/engraya/Codex-AI",
      webapp: "https://codex-ai-phi-two.vercel.app/",
    },
    {
      id: 8,
      title: "Medimatrix – Patient Record & Appointment Management System 🏥📋🩺",
      description:
        "Manage Patient's records, appointments, and more—all in one place",
      image: medimatrix,
      tags: ["Nextjs", "Typescript", "TailwindCSS", "Shadcn UI", "Appwrite", "Clerk", "Sentry"],
      category: "web app",
      github: "https://github.com/engraya/medimatrix",
      webapp: "https://medimatrix.vercel.app/",
    },
    {
      id: 9,
      title: "NetChat – AI-Powered Web Interaction Assistant 🤖💬🌐",
      description:
        "NetChat is an innovative AI-powered app that transforms how you interact with websites.",
      image: netchat,
      tags: ["Nextjs", "Typescript", "TailwindCSS", "Shadcn UI", "Clerk", "Vercel AI SDK", "UPSTASH"],
      category: "web app",
      github: "https://github.com/engraya/netchat",
      webapp: "https://netchat-io.vercel.app/",
    },
    {
      id: 10,
      title: "Detectify-AI – Real-Time Object Detection Powered by AI 🎯🧠📷",
      description:
        "Discover the future of object detection with Detectify AI.",
      image: detectify,
      tags: ["Nextjs", "Typescript", "TailwindCSS", "Threejs", "Tensorflowjs"],
      category: "web app",
      github: "https://github.com/engraya/detectify-ai",
      webapp: "https://detectify-ai.vercel.app/",
    },
    {
      id: 11,
      title: "PennyPlan – Smart Finance Management with AI-Powered Insights 💰📊🤖",
      description:
        "Manage your finances effortlessly with AI-powered insights and personalized financial advice",
      image: pennyplan,
      tags: ["Nextjs", "Typescript", "TailwindCSS", "Shadcn UI", "Drizzle", "PostgreSQL"],
      category: "web app",
      github: "https://github.com/engraya/pennyplan",
      webapp: "https://pennyplan.vercel.app/",
    },
    {
      id: 12,
      title: "PlanVault – Simplify Subscription Management & Payments 💼⚙️",
      description:
        "Fantastic UI/UX Payment platform that automates billing, invoicing, and subscription management for businesses.",
      image: planvault,
      tags: ["Nextjs", "Typescript", "TailwindCSS", "Stripe"],
      category: "web app",
      github: "https://github.com/engraya/PlanVault",
      webapp: "https://planvault.vercel.app/",
    },
    {
      id: 13,
      title: "Thankful Art – Create Personalized Thank You Cards in Seconds ✨💌🎨",
      description:
        "ThankfulArt is a web app designed to help you Create Your Perfect Thank You Card in Seconds",
      image: thankfulart,
      tags: ["Nextjs", "Typescript", "TailwindCSS", "Shadcn UI"],
      category: "web app",
      github: "https://github.com/engraya/thankful_art",
      webapp: "https://thankfulart.vercel.app/",
    },
    {
      id: 14,
      title: "Delectable – Discover Global Cuisines & Food Guides 🌍🍽️📸",
      description:
        "Embark on a gastronomic journey with Delectable – the ultimate food lover's paradise! 🌍🍽️",
      image: delectable,
      tags: ["React", "TailwindCSS", "Firebase", "Javascript"],
      category: "web app",
      github: "https://github.com/engraya/delectable-food-webapp",
      webapp: "https://delectable.vercel.app/",
    },
    {
      id: 15,
      title: "Motohub – Explore the World’s Sleekest, Most Stylish Cars 🌍🚗🔥b",
      description:
        "MotoHub - the hottest spot on the web to explore sleek, stylish, and cutting-edge cars from around the globe! 🌐🔥",
      image: motohub,
      tags: ["Nextjs", "Typescript", "TailwindCSS", "HeadlessUI", "React"],
      category: "web app",
      github: "https://github.com/engraya/motohub",
      webapp: "https://motohub-io.vercel.app/",
    },
    {
      id: 16,
      title: "Shelterium – Buy, Rent & Sell Properties with Real Estate App 🏠🔑📱",
      description:
        "Shelterium, the ultimate real estate app for buying, renting, and selling properties. 🏠🔑✨🌟",
      image: shelterium,
      tags: ["Nextjs", "Typescript", "TailwindCSS", "React"],
      category: "web app",
      github: "https://github.com/engraya/Shelterium",
      webapp: "https://shelterium.vercel.app/",
    },
    {
      id: 17,
      title: "QuickSumAI – Instantly Summarize Long Articles with AI 🧠📄⚡",
      description:
        "🌐 QuickSum AI is here to transform how you consume content!, a go-to solution for summarizing long articles in seconds. ⏳",
      image: quickSumAi,
      tags: ["React", "Typescript", "TailwindCSS", "Redux", "Redux Toolkit"],
      category: "web app",
      github: "https://github.com/engraya/QuickSum-AI",
      webapp: "https://quicksum-ai.vercel.app/",
    },
    {
      id: 18,
      title: "CoinStream – Real-Time Crypto Stats, Market Trends & Coin Insight 💹🪙",
      description:
        "Explore detailed information on a wide range of coins, from market capitalization to trading volume.",
      image: coinstream,
      tags: ["Nextjs", "Typescript", "TailwindCSS"],
      category: "web app",
      github: "https://github.com/engraya/coinStream",
      webapp: "https://coinstream.vercel.app/",
    },
      {
      id: 19,
      title: "Shopoholics – Ecommerce App for Seamless Online Shopping 🛍️🛒⚙️",
      description:
        "Shopoholics, an open-source Fullstack ecommerce app designed to revolutionize your online shopping experience! 🛒",
      image: shopoholics,
      tags: ["Nextjs", "Typescript", "TailwindCSS", "Sanity", "Stripe", "ShadCN", "React"],
      category: "web app",
      github: "https://github.com/engraya/shopoHolics",
      webapp: "https://shopoholics.vercel.app/",
    },
    {
      id: 20,
      title: "PromptHub – Discover, Organize & Share AI Prompts Effortlessly 💡📚🤖",
      description:
        "The ultimate platform for generating, sharing, and discovering prompts for every need",
      image: promptHub,
      tags: ["Nextjs", "Typescript", "Tailwind", "Next-Auth", "Shadcn UI"],
      category: "web app",
      github: "https://github.com/engraya/PromptHub",
      webapp: "https://prompthub-io.vercel.app/",
    },
    {
      id: 21,
      title: "Midin Project – Saving Communities Through Humanitarian Action 🌍❤️🤝",
      description:
        "Web Application for a dedicated humanitarian organization committed to creating positive change in communities.",
      image: midin,
      tags: ["React", "Tailwind", "Javascript"],
      category: "web app",
      github: "https://github.com/engraya/MIDIN-Org-Web-Project",
      webapp: "https://midin.vercel.app/",
    },
    {
      id: 22,
      title: "OrbitStaff – Smart Workforce & Staff Management Made Simple 🧑‍💼📊🚀",
      description:
        "OrbitStaff is a modern staff management solution designed to simplify how businesses manage workforce data.",
      image: orbitstaff,
      tags: ["React", "TailwindCSS", "Typescript", "Redux"],
      category: "web app",
      github: "https://github.com/engraya/orbitStaff",
      webapp: "https://orbitstaff.vercel.app/",
    },
      {
      id: 23,
      title: "Remidly – Smart Task & Reminder App to Organize Your Life ⏰📝✅",
      description:
        "Organize, prioritize, and conquer your to-dos with ease, whether it’s work, personal tasks, or long-term goals.",
      image: remindly,
      tags: ["React", "Nexjs", "Typescript", "TailwindCSS", "PostgreSQL", "ShadCnUI", "Clerk", "NeonDB"],
      category: "web app",
      github: "https://github.com/engraya/remindly",
      webapp: "https://remindly-io.vercel.app/",  
    },
        {
      id: 24,
      title: "TalentMatchAI – AI-Powered Intelligent Job Matching App",
      description:
        " TalentMatchAI analyzes your skills, matches them with the best job opportunities, and even helps you apply – all in one seamless experience! 🔍✨",
      image: talentmatch,
      tags: ["Nextjs", "Typescript", "TailwindCSS", "Shadcn UI", "AI", "Zustand"],
      category: "web app",
      github: "https://github.com/engraya/TalentMatch-AI",
      webapp: "https://talent-match-ai-jade.vercel.app/",
    },
      {
      id: 25,
      title: "Snapsavvy - Optimize your Photos Powered by AI 📷",
      description:
        " AI-powered application designed to revolutionize the way you enhance and restore your photos.",
      image: snapsavvy,
      tags: ["Nextjs", "Typescript", "TailwindCSS", "Shadcn UI", "Stripe", "Unsplash AI", "Clerk", "MongoDB"],
      category: "web app",
      github: "https://github.com/engraya/SnapSavvy",
      webapp: "https://snapsavvy.vercel.app/",
    },

 
   ] as const;
